[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "farmview"
version = "0.1.1"

[dependencies]
clap = "2.6.0"
rayon = "0.6.0"
serde = "0.8.20"
serde_derive = "0.8.20"
serde_json = "0.8.4"
ssh2 = "0.3.1"
tera = { git = "https://github.com/Keats/tera" }
xdg = "2.0.0"
time = "0.1"

[dependencies.handlebars]
default-features = false
features = ["serde_type"]
version = "0.22.0"

[dependencies.hyper]
default-features = false
features = ["serde-serialization"]
version = "0.9.11"

[dependencies.reroute]
default-features = false
features = ["serde-serialization"]
version = "0.3.0"

[dependencies.toml]
default-features = false
features = ["serde"]
version = "0.2"
