[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "farmview"
version = "0.1.0"

[dependencies]
clap = "2.6.0"
rayon = "0.4.0"
reroute = "0.2.2"
serde = "0.7.10"
serde_json = "0.7.1"
serde_macros = "0.7.10"
ssh2 = "0.2.12"
xdg = "2.0.0"

[dependencies.handlebars]
default-features = false
features = ["serde_type"]
version = "0.17.0"

[dependencies.toml]
default-features = false
features = ["serde"]
version = "0.1"

[dependencies.hyper]
features = ["serde-serialization"]
version = "0.9.9"
