[http]
	port = 8001

[default]
	login = "ubuntu"
	keypair = "USW2_KeyPair.pem"


[[hosts]]
	name = "Diffy"
	address = "diffy.diffbot.com"
	iface = "em1"
	disks = ["/dev/sda"]

[[hosts]]
	name = "Choi"
	iface = "em1"
	address = "choi.diffbot.com"
	disks = []
