refresh_delay = 30

[http]
	port = 8001

[default]
	login = "ubuntu"
	keypair = "USW2_KeyPair.pem"


[[hosts]]
	name = "Diffy"
	address = "diffy.diffbot.com"
	iface = "em1"

[[hosts]]
	name = "Choi"
	iface = "em1"
	address = "choi.diffbot.com"
	ignored_disks = []

[[hosts]]
	name = "Choi8"
	iface = "eno1"
	address = "choi8.diffbot.com"
	ignored_disks = []
